# Generated by Django 2.2.6 on 2019-10-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools_detail',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='affillicateno',
            field=models.CharField(max_length=100, verbose_name='School Affillicate Number'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='fax',
            field=models.CharField(max_length=255, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='logo',
            field=models.FileField(upload_to='documents/', verbose_name='School Logo'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='mobile',
            field=models.IntegerField(max_length=12, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='schoolname',
            field=models.CharField(max_length=255, unique=True, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='state',
            field=models.CharField(max_length=52, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='website',
            field=models.URLField(verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='schools_detail',
            name='zipcode',
            field=models.CharField(max_length=6, verbose_name='Zip Code'),
        ),
        migrations.CreateModel(
            name='School_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='User Name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('user_type', models.CharField(choices=[('', 'Select'), ('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student')], max_length=15, verbose_name='Choose User Type')),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Schools_detail')),
            ],
        ),
    ]
