# Generated by Django 2.2.6 on 2019-10-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20191010_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_users',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='User Name'),
        ),
    ]
