# Generated by Django 2.2.6 on 2019-10-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20191010_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools_detail',
            new_name='SchoolsDetail',
        ),
        migrations.RenameModel(
            old_name='School_Users',
            new_name='SchoolUser',
        ),
    ]
