# Generated by Django 2.2.6 on 2019-10-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20191011_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsdetail',
            name='usertype',
            field=models.CharField(default='Admin', max_length=50, null=True, verbose_name='User Type'),
        ),
    ]
