# Generated by Django 2.2.6 on 2019-10-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20191011_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsdetail',
            name='mobile',
            field=models.CharField(max_length=15, null=True, verbose_name='Mobile Number'),
        ),
    ]
