# Generated by Django 2.2.6 on 2019-10-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20191011_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolUser',
        ),
    ]
