# Generated by Django 2.2.6 on 2019-10-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_delete_schooluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('register_number', models.CharField(max_length=50, unique=True, verbose_name='Register Number')),
                ('admission_number', models.CharField(max_length=50, unique=True, verbose_name='Admission Number')),
                ('date_of_admission', models.DateField(verbose_name='Date Of Admission')),
                ('emergency_number', models.IntegerField(verbose_name='Emergency Number')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('adhar_number', models.IntegerField(unique=True, verbose_name='Adhar Number')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father Name')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Mother Name')),
                ('guardian_name', models.CharField(max_length=255, verbose_name='Guardian Name')),
                ('father_occupation', models.CharField(max_length=255, verbose_name='Father Occupation')),
                ('mother_occupation', models.CharField(max_length=255, verbose_name='Mother Occupation')),
                ('blood_group', models.CharField(max_length=25, verbose_name='Blood Group')),
                ('present_address', models.TextField(verbose_name='Present Address')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('religion', models.CharField(max_length=100, verbose_name='Religion')),
                ('caste', models.CharField(max_length=100, verbose_name='Caste')),
                ('Photo', models.FileField(upload_to='user_image/', verbose_name='Student Photo')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('user_type', models.CharField(default='student', max_length=10)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolsDetail')),
            ],
        ),
    ]
