# Generated by Django 2.2.6 on 2019-10-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_studentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='father_occupation',
            field=models.CharField(max_length=255, null=True, verbose_name='Father Occupation'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='guardian_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Guardian Name'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='mother_occupation',
            field=models.CharField(max_length=255, null=True, verbose_name='Mother Occupation'),
        ),
    ]
