# Generated by Django 2.2.6 on 2019-10-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20191012_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='emergency_number',
            field=models.CharField(max_length=50, verbose_name='Emergency Number'),
        ),
    ]
