# Generated by Django 2.2.6 on 2019-10-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20191012_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255, verbose_name='Staff Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Id')),
                ('mobile', models.IntegerField(verbose_name='Mobile Number')),
                ('emergency_number', models.IntegerField(verbose_name='Emergency Number')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('date_of_joining', models.DateField(verbose_name='Date Of Joining')),
                ('adhar_number', models.CharField(max_length=100, unique=True, verbose_name='Adhar Number')),
                ('degree', models.CharField(max_length=255, null=True, verbose_name='Degree')),
                ('designation', models.CharField(max_length=25, verbose_name='Designation')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('blood_group', models.CharField(max_length=25, verbose_name='Blood Group')),
                ('marital_status', models.CharField(choices=[('', 'Select'), ('single', 'Single'), ('married', 'Married')], max_length=15, verbose_name='Marital Status')),
                ('present_address', models.TextField(verbose_name='Present Address')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('bank_details', models.CharField(max_length=255, verbose_name='Bank Details')),
                ('Photo', models.FileField(upload_to='user_image/', verbose_name='Staff Photo')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('user_type', models.CharField(default='staff', max_length=12)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolsDetail')),
            ],
        ),
    ]
