# Generated by Django 2.2.6 on 2019-10-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20191014_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolsDetail')),
            ],
        ),
    ]
