# Generated by Django 2.2.6 on 2019-10-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exams', models.CharField(max_length=100, verbose_name='Exam Name')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolsDetail')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Section')),
            ],
        ),
    ]
