# Generated by Django 2.2.6 on 2019-10-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.CharField(max_length=50, null=True, verbose_name='Academic Year'),
        ),
    ]
