# Generated by Django 2.2.6 on 2019-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='academic_year',
            field=models.CharField(max_length=10, verbose_name='Academic Year'),
        ),
    ]
