# Generated by Django 2.2.6 on 2019-10-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20191015_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='pagination_count',
            field=models.IntegerField(verbose_name='Pagination Count'),
        ),
    ]
