# Generated by Django 2.2.6 on 2019-10-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_assignsubjectteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('student_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StudentDetail')),
            ],
        ),
    ]
