# Generated by Django 2.2.6 on 2019-10-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
