# Generated by Django 2.2.6 on 2019-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='adhar_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Adhar Number'),
        ),
    ]
