# Generated by Django 2.2.6 on 2019-10-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20191016_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_reg_no', models.CharField(max_length=50, verbose_name='Student Register Number')),
                ('mark', models.IntegerField(verbose_name='Mark')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Section')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject')),
            ],
        ),
    ]
