# Generated by Django 2.2.6 on 2019-10-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.AssignSubjectTeacher'),
        ),
    ]
