# Generated by Django 2.2.6 on 2019-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_mark_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Exam Name'),
        ),
    ]
