# Generated by Django 2.2.6 on 2019-10-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_mark_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='mark',
            name='exam_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Exam'),
        ),
    ]
