# Generated by Django 2.2.6 on 2019-10-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_auto_20191018_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='class_id',
            field=models.IntegerField(null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='section_id',
            field=models.IntegerField(null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='staff_id',
            field=models.IntegerField(null=True, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject_id',
            field=models.IntegerField(null=True, verbose_name='Subject'),
        ),
    ]
