# Generated by Django 2.2.6 on 2019-10-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_auto_20191021_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolSettings',
            new_name='SchoolSetting',
        ),
    ]
