# Generated by Django 2.2.6 on 2019-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_auto_20191021_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='class_id',
            field=models.IntegerField(null=True, verbose_name='Class Id'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Exam Id'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='section_id',
            field=models.IntegerField(null=True, verbose_name='Section Id'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='staff_id',
            field=models.IntegerField(null=True, verbose_name='Teacher Id'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject_id',
            field=models.IntegerField(null=True, verbose_name='Subject Id'),
        ),
        migrations.AlterField(
            model_name='schoolsdetail',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
