# Generated by Django 2.2.6 on 2019-10-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_auto_20191021_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolsDetail',
            new_name='SchoolDetail',
        ),
    ]
