# Generated by Django 2.2.6 on 2019-10-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_auto_20191021_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiary',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(verbose_name='Assigned Date')),
                ('diary_note', models.TextField(verbose_name='Dairy Notes')),
                ('homework_classwork', models.IntegerField(null=True, verbose_name='Home Work/ Class Work')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Section')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StaffDetail')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject')),
            ],
        ),
    ]
