# Generated by Django 2.2.6 on 2019-10-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_studentdiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam_id',
            field=models.IntegerField(null=True, verbose_name='Exam Id'),
        ),
    ]
