# Generated by Django 2.2.6 on 2019-10-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_auto_20191022_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetail',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='user_image/', verbose_name='Student Photo'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='adhar_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Adhar Number'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='blood_group',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caste'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Admission'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Number'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Name'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religion'),
        ),
    ]
