# Generated by Django 2.2.6 on 2019-10-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_auto_20191025_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='adhar_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adhar Number'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='adhar_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adhar Number'),
        ),
    ]
