# Generated by Django 2.2.6 on 2019-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_auto_20191025_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='is_class_teacher',
            field=models.CharField(blank=True, default='no', max_length=10, null=True, verbose_name='Class Teacher'),
        ),
    ]
